
name: AngularToDoList

trigger: [main, azure-pipelines]

pool:
  vmImage: 'windows-latest'

stages:
    - stage: Build
      jobs:
      - job: build_and_test
        displayName: Build and test
        steps:

        - task: NodeTool@0
          inputs:
           versionSpec: '18.x'
          displayName: 'Install Node.js'

        - task: Npm@1
          inputs:
            command: 'install'
          displayName: "npm install"

        - task: Npm@1
          inputs:
            command: custom
            customCommand: 'run lint'
          displayName: "Lint"

        - task: Npm@1
          inputs:
            command: custom
            customCommand: 'run build'
          displayName: "Build Angular app"

#        - task: Npm@1
#          inputs:
#            command: custom
#            customCommand: 'run test'
#          displayName: "Test Angular app"

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'dist/angular-primeng-todo'
            ArtifactName: 'app'
            publishLocation: 'Container'
